// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxflxacwbnumzgjgghyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4Zmx4YWN3Ym51bXpnamdnaHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0NDA1NTEsImV4cCI6MjA0OTAxNjU1MX0.Okzdjy8WMyImz8reCCM3ho1JvFKnmV3eV_A78le-4X0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);